tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LogoutView, LoginView
from usuario.views import login_view, logout_view
from debug_toolbar.toolbar import debug_toolbar_urls
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    #renderizar urls de productos a la app de productos
    path('productos/', include('productos.urls')),

    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    #renderizar urls de usuario a la app de usuario
    path('usuario/', include('usuario.urls')),
    #ursl de login
    path('login-class/', LoginView.as_view(template_name='usuarios/login.html'), name='login-class'),
    #url de logout
    path('logout-class/', LogoutView.as_view(next_page='login'), name='logout-class'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    )


urlpatterns += debug_toolbar_urls()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

productos/models.py
from django.db import models
from deep_translator import GoogleTranslator
# Create your models here.
# Categorias
# Proveedor
# Marca
# Productos

def traducir_texto(texto, entrada='es', salida='en'):
    try:
        traduccion = GoogleTranslator(source=entrada, target=salida).translate(texto)
        return traduccion
    except Exception as e:
        print(f"Error al traducir el texto: {e}")
        return texto

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def save(self, *args, **kwargs):
        if not self.nombre_en:
            self.nombre_en = traducir_texto(self.nombre, entrada='es', salida='en')
        if not self.nombre_fr:
            self.nombre_fr = traducir_texto(self.nombre, entrada='es', salida='fr')
        if not self.descripcion_en:
            self.descripcion_en = traducir_texto(self.descripcion, entrada='es', salida='en')
        if not self.descripcion_fr:
            self.descripcion_fr = traducir_texto(self.descripcion, entrada='es', salida='fr')
        super().save(*args, **kwargs)
        

class Proveedor(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name = 'Proveedor'
        verbose_name_plural = 'Proveedores'

class Marca(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'


class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(null=True, blank=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)
    activo = models.BooleanField(default=True)
    categorias = models.ManyToManyField(Categoria)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if not self.nombre_en:
            self.nombre_en = traducir_texto(self.nombre, entrada='es', salida='en')
        if not self.nombre_fr:
            self.nombre_fr = traducir_texto(self.nombre, entrada='es', salida='fr')
        if not self.descripcion_en:
            self.descripcion_en = traducir_texto(self.descripcion, entrada='es', salida='en')
        if not self.descripcion_fr:
            self.descripcion_fr = traducir_texto(self.descripcion, entrada='es', salida='fr')
        super().save(*args, **kwargs)
        

    def __str__(self):
        return f"{self.nombre} - ${self.precio}"
    
    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

class Imagen(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name='imagenes')
    imagen = models.ImageField(upload_to='imagenes/', null=True, blank=True)
    es_principal = models.BooleanField(default=False)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Imagen de {self.producto}"
    
    class Meta:
        verbose_name = 'Imagen'
        verbose_name_plural = 'Imagenes'

    
### modelos para el carrito de compras
from usuario.models import PerfilUsuario

class Carrito(models.Model):
    usuario = models.ForeignKey(PerfilUsuario, on_delete=models.CASCADE, related_name='carrito', null=True, blank=True)
    session_key = models.CharField(max_length=40, null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Carrito de {self.usuario}"

    class Meta:
        verbose_name = 'Carrito'
        verbose_name_plural = 'Carritos'

class ItemCarrito(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE, related_name='items')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        """
        Retorna un string que describe el item del carrito en formato:
        "Nombre del producto - cantidad de unidades"
        """
        return f"{self.producto} - {self.cantidad} unidades"

    class Meta:
        verbose_name = 'Item del Carrito'
        verbose_name_plural = 'Items del Carrito'

templates/categorias/eliminar_categoria.html
{% extends 'base.html' %}

{% block titulo %}
    Nueva Categoría
{% endblock %}

{% block css %}


{% endblock %}


{% block contenido %}


<section class="">
<div class="container">
    <h2>Eliminar Categoría</h2>
    <p>¿Estás seguro de que deseas eliminar "{{ categoria.nombre }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar Eliminación</button>
        <a href="{% url 'categorias' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
</section>

    
{% endblock %}  


{% block js %}


{% endblock %}

templates/categorias/lista_categorias.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block titulo %}
    {% trans "Categorias" %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'assets/css/categorias.css' %}">
{% endblock %}

{% block contenido %}

<div class="content-section">
    <h2>{% trans "Lista de Categorias" %}</h2>

    {% if user.is_authenticated %}
        {% if perms.productos.add_categoria %}
            <a href="{% url 'crear_categoria' %}" class="btn btn-primary">{% trans "Crear Categoria" %}</a>
            <a href="{% url 'ajax_categoria' %}" class="btn btn-primary">{% trans "Crear AJAX Categoria" %}</a>
        {% endif %}
    {% endif %}
    <table>
        <thead>
            <tr>
                <th>{% trans "Nombre" %}</th>
                <th>{% trans "Descripción" %}</th>
                {% if user.is_authenticated %}
                    {% if perms.productos.change_categoria %}
                        <th>{% trans "Editar" %}</th>
                    {% endif %}
                    {% if perms.productos.delete_categoria %}
                        <th>{% trans "Eliminar" %}</th>
                    {% endif %}
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for categoria in categorias %}
            <tr>
                <td>{{ categoria.nombre }}</td>
                <td>{{ categoria.descripcion }}</td>
                {% if user.is_authenticated %}
                    {% if perms.productos.change_categoria %}
                        <td><a href="{% url 'actualizar_categoria' categoria.id %}" class="btn btn btn-warning">{% trans "Editar" %}</a></td>
                    {% endif %}
                    {% if perms.productos.delete_categoria %}
                        <td><a href="{% url 'eliminar_categoria' categoria.id %}" class="btn btn-danger">{% trans "Eliminar" %}</a></td>
                    {% endif %}
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

{% block js %}


{% endblock %}

templates/categorias/nueva_categoria.html
{% extends 'base.html' %}

{% block titulo %}
    Nueva Categoría
{% endblock %}

{% block css %}

{% endblock %}


{% block contenido %}


<section class="">
            <h2>Crear Categoria</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
</section>

    
{% endblock %}  


{% block js %}


{% endblock %}